CREATE TABLE ord (qty INTEGER);

INSERT INTO ord VALUES(5);
INSERT INTO ord VALUES(NULL);
INSERT INTO ord VALUES(10);
INSERT INTO ord VALUES(8);
INSERT INTO ord VALUES(9);
INSERT INTO ord VALUES(13);

COMMIT;